ams:
  local:
    interop:
      host: https://158.85.0.60/
    customer:
      host: https://158.85.0.60/
    account:
      host: https://158.85.0.60/
    auth:
      host: https://158.85.0.60/
    tenants:
      - name: ibank-usa
        user: mifos
        password: password
        authtype: basic
        fspId: in02ibank-usa
      - name: ibank-india
        user: mifos
        password: password
        authtype: basic
        fspId: in02ibank-india
