camel:
  server-port: ${PORT:7000}
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

dfspids: "DFSPID"

zeebe:
  client:
    max-execution-threads: 100
    number-of-workers: 7
    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
  broker:
    contactpoint: "4ae8d42c-5f02-4e18-b4d4-f4d3d92fc824.zeebe.camunda.io:443"

ams:
  local:
    server-cert-check: false
    enabled: false
