camel:
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

dfspids: "DFSPID"

zeebe:
  client:
    max-execution-threads: 100
    number-of-workers: 8
    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
  broker:
    contactpoint: "zeebe-cluster-gateway/gateway:26500"

ams:
  local:
    server-cert-check: false
    enabled: false
