ams:
  local:
    interop:
      host: https://localhost:8443
    customer:
      host: https://localhost:8443
    account:
      host: https://localhost:8443
    auth:
      host: https://localhost:8443
    tenants:
      - name: ibank-usa
        user: mifos
        password: password
        authtype: basic
        fspId: in02ibank-usa
      - name: ibank-india
        user: mifos
        password: password
        authtype: basic
        fspId: in02ibank-india
